/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/AOtunmcjF66
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Caudex } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

caudex({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function Component() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <Link href="#" className="flex items-center justify-center" prefetch={false}>
          <DumbbellIcon className="h-6 w-6" />
          <span className="sr-only">El Club del Fitness</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            About
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            How It Works
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Products
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Contact
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32 xl:py-48">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
              <div>
                <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
                  Join El Club del Fitness Today!
                </h1>
                <p className="max-w-[600px] text-muted-foreground md:text-xl">
                  Get premium fitness products delivered to your door every month.
                </p>
                <div className="flex flex-col gap-2 min-[400px]:flex-row mt-6">
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    Join Now
                  </Link>
                </div>
              </div>
              <img
                src="/placeholder.svg"
                width="550"
                height="310"
                alt="Hero"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
              />
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-muted">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">About El Club del Fitness</h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  El Club del Fitness is a monthly subscription service that delivers premium fitness products to your
                  door. From proteins and pre-workout supplements to stylish apparel and accessories, we've got
                  everything you need to stay motivated and reach your fitness goals. Join our community of fitness
                  enthusiasts and let us help you achieve your best self.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">How It Works</h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Joining El Club del Fitness is easy. Follow these three simple steps:
                </p>
              </div>
              <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-3 lg:gap-12">
                <div className="grid gap-1">
                  <ClipboardIcon className="mx-auto h-12 w-12 text-primary" />
                  <h3 className="text-xl font-bold">Choose your subscription level</h3>
                  <p className="text-muted-foreground">
                    Select the subscription plan that best fits your fitness needs and budget.
                  </p>
                </div>
                <div className="grid gap-1">
                  <TruckIcon className="mx-auto h-12 w-12 text-primary" />
                  <h3 className="text-xl font-bold">Receive your fitness box every month</h3>
                  <p className="text-muted-foreground">
                    Your personalized box of premium fitness products will be delivered to your door.
                  </p>
                </div>
                <div className="grid gap-1">
                  <ZapIcon className="mx-auto h-12 w-12 text-primary" />
                  <h3 className="text-xl font-bold">Enjoy and stay motivated</h3>
                  <p className="text-muted-foreground">
                    Use your new fitness products and join our supportive community to stay on track.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Products We Offer</h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Each month, your El Club del Fitness box will include a variety of premium fitness products to help
                  you reach your goals.
                </p>
              </div>
              <div className="mx-auto grid max-w-5xl grid-cols-2 gap-6 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5">
                <div className="flex flex-col items-center justify-center space-y-2">
                  <img
                    src="/placeholder.svg"
                    width="120"
                    height="120"
                    alt="Protein Powder"
                    className="rounded-full object-cover"
                  />
                  <p className="text-sm font-medium">Protein Powder</p>
                </div>
                <div className="flex flex-col items-center justify-center space-y-2">
                  <img
                    src="/placeholder.svg"
                    width="120"
                    height="120"
                    alt="Pre-Workout"
                    className="rounded-full object-cover"
                  />
                  <p className="text-sm font-medium">Pre-Workout</p>
                </div>
                <div className="flex flex-col items-center justify-center space-y-2">
                  <img
                    src="/placeholder.svg"
                    width="120"
                    height="120"
                    alt="Apparel"
                    className="rounded-full object-cover"
                  />
                  <p className="text-sm font-medium">Apparel</p>
                </div>
                <div className="flex flex-col items-center justify-center space-y-2">
                  <img
                    src="/placeholder.svg"
                    width="120"
                    height="120"
                    alt="Accessories"
                    className="rounded-full object-cover"
                  />
                  <p className="text-sm font-medium">Accessories</p>
                </div>
                <div className="flex flex-col items-center justify-center space-y-2">
                  <img
                    src="/placeholder.svg"
                    width="120"
                    height="120"
                    alt="Supplements"
                    className="rounded-full object-cover"
                  />
                  <p className="text-sm font-medium">Supplements</p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-muted">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Pricing</h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Choose the subscription plan that best fits your fitness needs and budget.
                </p>
              </div>
              <div className="mx-auto grid max-w-5xl grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
                <div className="bg-background rounded-lg shadow-md p-6 flex flex-col justify-between">
                  <div>
                    <h3 className="text-2xl font-bold">Basic</h3>
                    <p className="text-4xl font-bold my-4">$29/mo</p>
                    <ul className="space-y-2 text-muted-foreground">
                      <li>
                        <CheckIcon className="mr-2 inline-block h-4 w-4 text-green-500" />
                        1 Fitness Box per month
                      </li>
                      <li>
                        <CheckIcon className="mr-2 inline-block h-4 w-4 text-green-500" />
                        Protein Powder
                      </li>
                      <li>
                        <CheckIcon className="mr-2 inline-block h-4 w-4 text-green-500" />
                        Pre-Workout
                      </li>
                    </ul>
                  </div>
                  <div className="mt-6">
                    <Link
                      href="#"
                      className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                      prefetch={false}
                    >
                      Join Basic
                    </Link>
                  </div>
                </div>
                <div className="bg-background rounded-lg shadow-md p-6 flex flex-col justify-between">
                  <div>
                    <h3 className="text-2xl font-bold">Premium</h3>
                    <p className="text-4xl font-bold my-4">$49/mo</p>
                    <ul className="space-y-2 text-muted-foreground">
                      <li>
                        <CheckIcon className="mr-2 inline-block h-4 w-4 text-green-500" />
                        1 Fitness Box per month
                      </li>
                      <li>
                        <CheckIcon className="mr-2 inline-block h-4 w-4 text-green-500" />
                        Protein Powder
                      </li>
                      <li>
                        <CheckIcon className="mr-2 inline-block h-4 w-4 text-green-500" />
                        Pre-Workout
                      </li>
                      <li>
                        <CheckIcon className="mr-2 inline-block h-4 w-4 text-green-500" />
                        Apparel
                      </li>
                      <li>
                        <CheckIcon className="mr-2 inline-block h-4 w-4 text-green-500" />
                        Accessories
                      </li>
                    </ul>
                  </div>
                  <div className="mt-6">
                    <Link
                      href="#"
                      className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                      prefetch={false}
                    >
                      Join Premium
                    </Link>
                  </div>
                </div>
                <div className="bg-background rounded-lg shadow-md p-6 flex flex-col justify-between">
                  <div>
                    <h3 className="text-2xl font-bold">Elite</h3>
                    <p className="text-4xl font-bold my-4">$79/mo</p>
                    <ul className="space-y-2 text-muted-foreground">
                      <li>
                        <CheckIcon className="mr-2 inline-block h-4 w-4 text-green-500" />
                        1 Fitness Box per month
                      </li>
                      <li>
                        <CheckIcon className="mr-2 inline-block h-4 w-4 text-green-500" />
                        Protein Powder
                      </li>
                      <li>
                        <CheckIcon className="mr-2 inline-block h-4 w-4 text-green-500" />
                        Pre-Workout
                      </li>
                      <li>
                        <CheckIcon className="mr-2 inline-block h-4 w-4 text-green-500" />
                        Apparel
                      </li>
                      <li>
                        <CheckIcon className="mr-2 inline-block h-4 w-4 text-green-500" />
                        Accessories
                      </li>
                      <li>
                        <CheckIcon className="mr-2 inline-block h-4 w-4 text-green-500" />
                        Supplements
                      </li>
                    </ul>
                  </div>
                  <div className="mt-6">
                    <Link
                      href="#"
                      className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                      prefetch={false}
                    >
                      Join Elite
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}

function CheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 6 9 17l-5-5" />
    </svg>
  )
}


function ClipboardIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="8" height="4" x="8" y="2" rx="1" ry="1" />
      <path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2" />
    </svg>
  )
}


function DumbbellIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14.4 14.4 9.6 9.6" />
      <path d="M18.657 21.485a2 2 0 1 1-2.829-2.828l-1.767 1.768a2 2 0 1 1-2.829-2.829l6.364-6.364a2 2 0 1 1 2.829 2.829l-1.768 1.767a2 2 0 1 1 2.828 2.829z" />
      <path d="m21.5 21.5-1.4-1.4" />
      <path d="M3.9 3.9 2.5 2.5" />
      <path d="M6.404 12.768a2 2 0 1 1-2.829-2.829l1.768-1.767a2 2 0 1 1-2.828-2.829l2.828-2.828a2 2 0 1 1 2.829 2.828l1.767-1.768a2 2 0 1 1 2.829 2.829z" />
    </svg>
  )
}


function TruckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14 18V6a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2v11a1 1 0 0 0 1 1h2" />
      <path d="M15 18H9" />
      <path d="M19 18h2a1 1 0 0 0 1-1v-3.65a1 1 0 0 0-.22-.624l-3.48-4.35A1 1 0 0 0 17.52 8H14" />
      <circle cx="17" cy="18" r="2" />
      <circle cx="7" cy="18" r="2" />
    </svg>
  )
}


function ZapIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 14a1 1 0 0 1-.78-1.63l9.9-10.2a.5.5 0 0 1 .86.46l-1.92 6.02A1 1 0 0 0 13 10h7a1 1 0 0 1 .78 1.63l-9.9 10.2a.5.5 0 0 1-.86-.46l1.92-6.02A1 1 0 0 0 11 14z" />
    </svg>
  )
}
